permalink: /:year/:month/:day/:title.html   #博文的固定链接
paginate: 10                                #分页时每页博文数量
author:                                     #自定义常亮
  name: sheeeeep
  email: 281591919@qq.com
markdown: redcarpet                         #markdown解释器